import 'package:flutter/material.dart';
const Color backgroundColor = Color(0xFFF8F9FE);
const Color whiteColor = Color(0xFFFFFFFF);
const Color textColor = Color(0xFF525F7F);
const Color textGreyColor = Color(0xFF8898AA);
const Color lightColor = Color(0xFF8993C6);
const Color lightWhiteColor = Color(0xFFCFD4EA);
const Color darkBlueColor = Color(0xFF172B4D);
const Color unSelectColor = Color(0xFFA7ADBE);
const Color blackColor = Color(0xFF000000);
const Color transparentBlackColor = Color(0x71000000);
const Color skyColor = Color(0xFF5E72E4);
const Color blueColor = Color(0xFF213AC8);
const Color cyanColor = Color(0xFF11CBED);
const Color greyColor = Color(0xFF707070);
const Color lightGreyColor = Color(0xFFF7F7F7);
const Color yellowColor = Color(0xFFDFB81B);
const Color transparentColor = Colors.transparent;